name: NestJS CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: donacoop_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "PORT=3001" >> .env
          echo "NODE_ENV=test" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=donacoop_test" >> .env
          echo "JWT_SECRET=testsecret" >> .env
          echo "JWT_EXPIRES_IN=1d" >> .env

      - name: Build project
        run: npm run build

      - name: Run migrations
        run: npm run migration:run

      - name: Run tests
        run: npm test

      # - name: Run e2e tests
      #   run: npm run test:e2e
